services:
  - type: web
    name: travel-planner-backend
    runtime: docker
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://travel-mysql-mr-b549.d.aivencloud.com:18032/travel?sslMode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: NOMINATIM_URL
        value: https://nominatim.openstreetmap.org
      - key: NOMINATIM_USER_AGENT
        sync: false
      - key: ORS_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://team-project-243.vercel.app
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: '3600000'

  - type: web
    name: travel-planner-backend-staging
    runtime: docker
    branch: dev
    rootDir: backend
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://travel-mysql-mr-b549.d.aivencloud.com:18032/travel_staging?sslMode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: NOMINATIM_URL
        value: https://nominatim.openstreetmap.org
      - key: NOMINATIM_USER_AGENT
        sync: false
      - key: ORS_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: '3600000'
