jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
supabase:
  s3:
    endpoint: ${SUPABASE_S3_ENDPOINT}
    region: ${SUPABASE_S3_REGION:eu-west-1}
    access-key-id: ${SUPABASE_S3_ACCESS_KEY_ID}
    secret-access-key: ${SUPABASE_S3_SECRET_ACCESS_KEY}
    bucket: ${SUPABASE_STORAGE_BUCKET:user-images-staging}
spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/travel_planner}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
